### PR TITLE
Ready for review 

### PR DESCRIPTION
**Pull request by MuriloRoque**
This is a clone website of [Mint Sign-Up page form](https://accounts.intuit.com/signup.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Ftask%3DS).

We applied Form tags and positioning rules in HTML and CSS.

### CODE REVIEW

**Comment by kubilaycaglayan** [comment]
[Click for Live Link](https://rawcdn.githack.com/MuriloRoque/signup-form/600ff0ee993b0eecec1518721ccd746641cc14f6/index.html)

Hello TSE,

We've finished our project.

With all of our respects...

**Comment by majovanilla** [comment]
Hey Team, 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯

- The page looks almost exactly as the original one. :heavy_check_mark: 

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

**General corrections**
- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have just one error this time. Please fix it.
Screenshot from 2020-02-24 11-30-22

- You are missing the stylelint.config.js on your project. Please read and follow the [instructions](https://github.com/microverseinc/linters-config/tree/master/css) to set the linters on your project and correct the errors.

- Improve your Readme file. It should be descriptive of the project. Here's a great [template](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) I strongly recommend you to use. In this case, you are forgetting to put the contributors' information, which is super important! 

-Please write meaningful pull request messages. Check this [example](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
Although you included a message to the TSE, this doesn't count as a PR message. Next time your project could be marked as invalid.

**Project specifics**
- You are using just one image for the elements on top of the form. You should be using one image per logo and position them correctly. 

- You should be using a form tag enclosing the inputs you already have. This is a Microverse requirement. See screenshot [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png)

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by kubilaycaglayan** [comment]
[Click For Live Link](https://rawcdn.githack.com/MuriloRoque/signup-form/7439b5a56ae7624e37e8f52a6dc5d38faa6c0847/index.html)

**Validator Error:** We added character encoding to the head tag.
**Missing File:** We added the stylelint.config.js
**Readme:** Updated README file, added authors section. 
**PR Message:** We detailed our PR message.
**Logo:** On the top of the form we used one image per logo.
**Form Tag:** We added Form tag.

**Review by MarioDena — CHANGES_REQUESTED** [review]
## Hello Team. my name is Mario Enrique Delgado Naranjo.

Great job on fixing the required changes for your project!! :fire::fire: 
However this project still need a few fixes to be approved.

## Required Changes:

Your project is not passing the linter checks, please be sure to be using the correct config for your project
You can find all linters here: https://github.com/microverseinc/linters-config


Please Update your Project Description, right now the legend _"No description, website, or topics provided. "_ Is shown.

## After making the required changes please re-submit your project for review.

Cheers!! :smiley:

**Review by MarioDena — CHANGES_REQUESTED** [review]
Ignore This comment. Sorry!

**Comment by kubilaycaglayan** [comment]
[Click For Live Link](https://rawcdn.githack.com/MuriloRoque/signup-form/7439b5a56ae7624e37e8f52a6dc5d38faa6c0847/index.html)

**Correct Config File:** Edited.
**Linter Errors:** All fixed.
**Project Description:** Added.

**Review by rOluochKe — APPROVED** [review]
Hello Team
### Good job for the work done and making the reviews changes :clap: and congratulations your project passes review :boom: :100: therefore, I approve of this project.
### You can merge and submit a project completion form from your dashboard. Good luck in the nect project.
- Happy coding!

**Pull request merged**
